package br.ufpb.dcx.agroplus.model;
public class Estoque {
 private int id,produtoId; private String nomeProduto,unidadeMedida,localArmazenamento; private float quantidadeAtual,estoqueMinimo,estoqueMaximo;
 public Estoque(int id,int produtoId,String nomeProduto,float quantidadeAtual,String unidadeMedida,float estoqueMinimo,float estoqueMaximo,String localArmazenamento){this.id=id;this.produtoId=produtoId;this.nomeProduto=nomeProduto;this.quantidadeAtual=quantidadeAtual;this.unidadeMedida=unidadeMedida;this.estoqueMinimo=estoqueMinimo;this.estoqueMaximo=estoqueMaximo;this.localArmazenamento=localArmazenamento;}
 public void registrarEntrada(float quantidade,String notaFiscal){if(quantidade<=0)throw new IllegalArgumentException("A quantidade de entrada deve ser maior que zero.");if(quantidadeAtual+quantidade>estoqueMaximo)System.out.println("[AVISO] A entrada excede o estoque máximo ("+estoqueMaximo+"). Ajustando quantidade.");quantidadeAtual+=quantidade;}
 public void registrarSaida(float quantidade,String motivo){if(quantidade<=0)throw new IllegalArgumentException("A quantidade de saída deve ser maior que zero.");if(quantidadeAtual-quantidade<0)throw new IllegalStateException("Saldo de estoque insuficiente para realizar esta saída.");quantidadeAtual-=quantidade;}
 public boolean verificarEstoqueBaixo(){return quantidadeAtual<=estoqueMinimo;}
 public String gerarAlerta(){if(verificarEstoqueBaixo())return String.format("[ALERTA] Estoque de %s está baixo! Atual: %.2f %s (Mínimo: %.2f %s)",nomeProduto,quantidadeAtual,unidadeMedida,estoqueMinimo,unidadeMedida);return null;}
 public int getId(){return id;} public void setId(int v){id=v;} public int getProdutoId(){return produtoId;} public void setProdutoId(int v){produtoId=v;} public String getNomeProduto(){return nomeProduto;} public void setNomeProduto(String v){nomeProduto=v;} public float getQuantidadeAtual(){return quantidadeAtual;} public void setQuantidadeAtual(float v){quantidadeAtual=v;} public String getUnidadeMedida(){return unidadeMedida;} public void setUnidadeMedida(String v){unidadeMedida=v;} public float getEstoqueMinimo(){return estoqueMinimo;} public void setEstoqueMinimo(float v){estoqueMinimo=v;} public float getEstoqueMaximo(){return estoqueMaximo;} public void setEstoqueMaximo(float v){estoqueMaximo=v;} public String getLocalArmazenamento(){return localArmazenamento;} public void setLocalArmazenamento(String v){localArmazenamento=v;}
}
